import numpy as np
from .similarity_matrices import embed_papers_by_abstract, jaccard_coathorship_similarity, graph_theoretic_dist, embed_papers_by_keywords
from ._utils import dimension_reduction, getType
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from itertools import chain
import networkx as nx

class UnionGraph():
    """
    Create distance matrices for Paper nodes, Author nodes, and distances between Papers and Authors,
    then creates a unified distance matrix composed of those distance matrices normalized, and input to
    a traditional dimension reduction algorithm (t-SNE, UMAP etc)

    Parameters
    ----------
    G : 
        NetworkX bipartite graph of papers and authors
    
    paper_type :
        'type' of paper nodes

    author_type :
        'type' of author nodes

    embed_papers_by : one of 'abstract' or 'keywords'
        Create sentence embedding on the abstract or the keywords of the papers

    paper_embed_data_loc : 
        Where is keyword or abstract data of paper node located
    """
    def __init__(self, G: nx.classes.graph.Graph, paper_type:str='Paper', author_type:str='Author', embed_papers_by:str='abstract', paper_embed_data_loc='Abstract', verbose: int = 0):
        self.G = G
        self.paper_type = paper_type
        self.author_type = author_type
        self.embed_papers_by = embed_papers_by
        self.paper_embed_data_loc = paper_embed_data_loc
        self.verbose = verbose

    
    def _paper_sim(self, n_neighbors=15, mode='connectivity',):
        """
        Returns
        -------

        (paper_list, distance_matrix) tuple, where distance_matrix is the distance matrix of the embedding
        of the n_neighbors nearest neighbors, and paper_list is the order of nodes
        """
        if self.embed_papers_by == 'abstract' or self.embed_papers_by == 'data':
            paper_embed_method = embed_papers_by_abstract
        elif self.embed_papers_by == 'keywords':
            paper_embed_method = embed_papers_by_keywords
        else:
            raise ValueError(f"embed_paper_by should be one of 'abstract' or 'keywords'. Was {self.embed_papers_by} instead.")
        
        paper_emb_pos = paper_embed_method(self.G, False, self.paper_embed_data_loc, self.paper_type)
        paper_list = list(paper_emb_pos.keys())
        nn = NearestNeighbors(n_neighbors=n_neighbors).fit(list(paper_emb_pos.values())).kneighbors_graph(mode=mode).toarray()

        nn = nn + nn.T
        nn = MinMaxScaler().fit_transform(nn)

        if self.verbose > 1:
            print("Created distance matrix of rich emb.")
        
        return paper_list, nn
    
    def fruchtermann(self, author_weight=1, paper_weight=1):
        """
        Keeps paper-author edges and introduces paper-paper and author-author edges too. Paper-Paper edges are drawn between
        the 15 nearest neighbors in the sentence embedding space. The weight is 1 if the two Paper are nearest neighbors of each other
        in the sentence embedding, and 0.5 if only one paper is a nearest neighbor of the other. Author-Author edges are drawn by considering
        the Jaccard similarity of the authors by coauthored papers. An embedding is then generated by simply calling NetworkX's implementation
        of the Fruchtermann-Reingold algorithm (spring_layout).
        """
        union_graph = self.get_union_graph(author_weight, paper_weight)

        # print(union_graph.nodes())
        pos = nx.spring_layout(union_graph)
        return pos
    
    def kamada_kawai(self, author_weight=1, paper_weight=1):
        """
        Keeps paper-author edges and introduces paper-paper and author-author edges too. Paper-Paper edges are drawn between
        the 15 nearest neighbors in the sentence embedding space. The weight is 1 if the two Paper are nearest neighbors of each other
        in the sentence embedding, and 0.5 if only one paper is a nearest neighbor of the other. Author-Author edges are drawn by considering
        the Jaccard similarity of the authors by coauthored papers. An embedding is then generated by simply calling NetworkX's implementation
        of the Kamada-Kawai algorithm.
        """
        union_graph = self.get_union_graph(author_weight, paper_weight)
        return nx.kamada_kawai_layout(union_graph)

    def get_union_graph(self, author_weight=1, paper_weight=1, label_edges=False):
        # Create Papers graph
        paper_list, paper_nn = self._paper_sim(mode='connectivity')
        paper_nn *= paper_weight
        Papers = nx.from_numpy_array(paper_nn, nodelist=paper_list)
        if label_edges:
            for _, _, data in Papers.edges(data=True):
                data['relation'] = 'p2p'

        if self.verbose:
            print("Created rich graph")

        # Create Authors graph
        auth_jac_emb, author_list = jaccard_coathorship_similarity(self.G, ret_nodelist=True, sparse_type=self.author_type)
        np.fill_diagonal(auth_jac_emb, 0) # No self-loop edges
        auth_jac_emb = MinMaxScaler().fit_transform(auth_jac_emb)
        auth_jac_emb *= author_weight
        Authors = nx.from_numpy_array(auth_jac_emb, nodelist=author_list)
        if label_edges:
            for _, _, data in Authors.edges(data=True):
                data['relation'] = 'a2a'

        if self.verbose:
            print("Created sparse graph")

        # Create union graph
        union_graph = nx.compose_all([self.G, Papers, Authors])
        if label_edges:
            for _, _, data in union_graph.edges(data=True):
                if 'relation' not in data:
                    data['relation'] = 'p2a'

        if self.verbose:
            print("Created union graph")                    
        return union_graph

    def dim_reduction(self, alg='UMAP', pca_dim=50):

        """
        Create a distance measure between nodes. Three types of distances are considered separately:
            1. Paper-Paper distances
            2. Paper-Author distances
            3. Author-Author distances

        Paper-Paper distances are determined by the pairwise distances between papers in the
        sentence embedding. Paper-Author distances are determined by the graph-theoretic distance
        between a Paper node and an Author node. Author-Author distances are determined by getting
        1 - the Jaccard similarity of coauthorship between two Authors. All three types of distances
        are separately scaled such that the maximum distance in each category equals 1. The resulting
        distance matrix is then inputted into a dimension reduction algorithm such as UMAP or t-SNE.
        """
        if self.embed_papers_by == 'abstract' or self.embed_papers_by == 'data':
            paper_embed_method = embed_papers_by_abstract
        elif self.embed_papers_by == 'keywords':
            paper_embed_method == embed_papers_by_keywords
        else:
            raise ValueError(f"self.embed_papers_by has to be one of 'abstract' or 'keywords'. Instead got {self.embed_papers_by}")
        p2p_dict = paper_embed_method(self.G, False, self.paper_embed_data_loc, self.paper_type)
        paper_nodes = list(p2p_dict.keys())
        p2p_vec = np.array(list(p2p_dict.values()))
        p2p_vec = PCA(n_components=pca_dim).fit_transform(p2p_vec)
        p2p_dist = pairwise_distances(p2p_vec)

        if self.verbose:
            print("Distance matrix: Created rich-rich block.")

        jac_sim_mat, author_nodes = jaccard_coathorship_similarity(self.G, ret_nodelist=True, sparse_type=self.author_type)
        a2a_dist = 1 - jac_sim_mat

        if self.verbose:
            print("Distance matrix: Created sparse-sparse block.")

        node_order = paper_nodes + author_nodes
        p2a_dist = graph_theoretic_dist(self.G, paper_type=self.paper_type, author_type=self.author_type, node_order=node_order)

        if self.verbose:
            print("Distance matrix: Created rich-sparse block")
    
        # Normalize
        p2p_dist, a2a_dist, p2a_dist = [MinMaxScaler().fit_transform(X) for X in [p2p_dist, a2a_dist, p2a_dist]]

        # Merge distance matrices to form full dist matrix
        # A B
        # C D
        AB = np.concatenate((p2p_dist, p2a_dist), axis=1)
        CD = np.concatenate((p2a_dist.T, a2a_dist), axis=1)
        full_dist = np.concatenate((AB, CD), axis=0)

        if self.verbose:
            print("Distance matrix created. Running dimension reduction.")

        Y = dimension_reduction(full_dist, alg, X_is_dist=True)

        pos = {node: vec for node, vec in zip(node_order, Y)}
        return pos

        for (node, data), vec in zip(chain(getType(self.G, self.paper_type).nodes(data=True), getType(self.G, self.author_type).nodes(data=True)), Y):
            data['x'] = vec[0]
            data['y'] = vec[1]

        return full_dist, Y

