import networkx as nx
from .similarity_matrices import embed_papers_by_abstract, embed_papers_by_keywords, jaccard_coathorship_similarity
from sklearn.neighbors import NearestNeighbors
from scipy.linalg import orthogonal_procrustes
import numpy as np

def procrustes_layout(
        G: nx.classes.graph.Graph,
        paper_type: str='Paper',
        author_type: str='Author',
        embed_papers_by: str='abstract', # either 'abstract' or 'keywords'
        paper_embed_data_loc: str='Abstract',
        transform_author: bool=True, # if False, gets GM 
):
    """
    Paper nodes and Author nodes are first embedded independent to their relationship with each other. For the Paper nodes,
    a sentence embedding is generated by training a transformer on the abstract or the keywords of the paper. Then,
    a graph of Paper nodes is generated with edges of weight=1 between 2 nodes where one is among the 15 nearest neighbors
    of the other. An embedding of this graph is created using the Fruchtermann-Reingold layout algorithm. The Author nodes
    are similarly embedded, this time drawing edges between authors where the weight of an edge is equal to the Jaccard
    similarity of the coauthorship of papers between two authors.
    
    Now, the two separate Author (A_emb) and Paper (P_emb) embeddings are scaled, translated, rotated, and flipped/mirrored in such a way
    that maximally preserves the relationship between authors and papers. This is done by choosing one of the node types, say for example
    the Authors, and creating a new embedding for the Author nodes A_emb* created by placing Author nodes in the geometric center of the
    Paper nodes it shares an edge with. Then, we find the optimal transform that can be applied on A_emb* in order to minimize the Procrustes
    distance between A_emb and A_emb*. Then, this transformation is applied to P_emb. 

    Thus, priority is first assigned to preserving Author-Author and Paper-Paper relationships as well as possible, and then the embeddings
    are transformed such that the Paper-Author relationships are preserved within the constraint of maintaining optimal Paper-Paper and
    Author-Author relationships.  


    Parameters
    ----------

    G : NetworkX Graph
        Bipartite graph with nodes of two types: papers and authors
    
    paper_type : str
        'type' attribute of paper nodes
    
    author_type : str
        'type' attribute of author nodes

    embed_papers_by : one of 'abstract' or 'keywords'
        If 'abstract', embeds papers from abstract
        If 'keywords', embeds papers from paper keywords

    paper_embed_data_loc : str
        Name of attribute where either abstract or set of keywords is stored
    
    transform_author : bool
        If True, the the geometric mean of the (author) neighbors of the paper nodes is taken as the pseudo author embedding
        and Procrustes analysis is applied. The same transformation applied to the pseudo-embedding is then applied to the
        actual author embedding.
        If False, the role of paper nodes and author nodes switches
    """
    if embed_papers_by == 'abstract' or embed_papers_by == 'data':
        paper_embed_method = embed_papers_by_abstract
    elif embed_papers_by == 'keywords':
        paper_embed_method = embed_papers_by_keywords
    else:
        raise ValueError(f"embed_paper_by should be one of 'abstract' or 'keywords'. Was {embed_papers_by} instead.")
    
    # Create embeddings of Papers and Authors

    paper_emb_pos = paper_embed_method(G, False, paper_embed_data_loc, paper_type)
    paper_list = list(paper_emb_pos.keys())
    nn = NearestNeighbors(n_neighbors=15).fit(list(paper_emb_pos.values())).kneighbors_graph().toarray()
    Papers = nx.from_numpy_array(nn, nodelist=paper_list)
    paper_pos = nx.spring_layout(Papers)

    auth_jac_emb, author_list = jaccard_coathorship_similarity(G, ret_nodelist=True, sparse_type=author_type)
    Authors = nx.from_numpy_array(auth_jac_emb, nodelist=author_list)
    author_pos = nx.spring_layout(Authors)

    # Transform by minimizing Procrustes
    pos1, pos2 = (paper_pos, author_pos) if transform_author else (author_pos, paper_pos)
    emb1 = np.array(list(pos1.values()))
    emb2 = np.array(list(pos2.values()))
    emb2_gm = np.array([np.mean([pos2[nbr] for nbr in G[node]], 0) for node in pos1.keys()])
    
    mean1 = np.mean(emb1, 0)
    mean2_gm = np.mean(emb2_gm, 0)
    emb1 -= mean1
    emb2 -= mean2_gm
    emb2_gm -= mean2_gm
    
    norm1 = np.linalg.norm(emb1)
    norm2_gm = np.linalg.norm(emb2_gm)
    emb1 /= norm1
    emb2 /= norm2_gm
    emb2_gm /= norm2_gm

    # Find transformation after flipping
    emb2_gm_flipped = -emb2_gm
    R_flip, s_flip = orthogonal_procrustes(emb1, emb2_gm_flipped)
    emb2_gm_flipped_transformed = (emb2_gm_flipped @ R_flip.T) * s_flip
    mse_flip = np.mean(np.linalg.norm(emb2_gm_flipped_transformed - emb1, axis=1))

    # Find transformation without flipping
    R, s = orthogonal_procrustes(emb1, emb2_gm)
    emb2_gm_transformed = (emb2_gm @ R.T) * s
    mse_no_flip = np.mean(np.linalg.norm(emb2_gm_transformed - emb1, axis=1))

    # Flip or no flip?
    if mse_flip < mse_no_flip:
        emb2 = ((-emb2) @ R_flip.T) * s_flip
    else:
        emb2 = (emb2 @ R.T) * s

    # Update positions
    pos1 = {key: value for key, value in zip(pos1.keys(), emb1)}
    pos2 = {key: value for key, value in zip(pos2.keys(), emb2)}

    pos = pos1 | pos2
    return pos

def box_procrustes_layout(
    G: nx.classes.graph.Graph,
    paper_type: str='Paper',
    author_type: str='Author',
    embed_papers_by: str='abstract', # either 'abstract' or 'keywords'
    paper_embed_data_loc: str='Abstract',
    transform_author: bool=True, # if False, gets GM 
    verbose: int = 0,
):
    if verbose > 5:
        print(f"Running box procrustes layout with transform_author={transform_author}")

    if embed_papers_by == 'abstract' or embed_papers_by == "data":
        paper_embed_method = embed_papers_by_abstract
    elif embed_papers_by == 'keywords':
        paper_embed_method = embed_papers_by_keywords
    else:
        raise ValueError(f"embed_paper_by should be one of 'abstract' or 'keywords'. Was {embed_papers_by} instead.")
    
    # Create embeddings of Papers and Authors

    paper_emb_pos = paper_embed_method(G, False, paper_embed_data_loc, paper_type)
    paper_list = list(paper_emb_pos.keys())
    nn = NearestNeighbors(n_neighbors=15).fit(list(paper_emb_pos.values())).kneighbors_graph().toarray()
    Papers = nx.from_numpy_array(nn, nodelist=paper_list)
    paper_pos = nx.spring_layout(Papers)

    if verbose:
        print("Created rich part.")

    auth_jac_emb, author_list = jaccard_coathorship_similarity(G, ret_nodelist=True, sparse_type=author_type)
    Authors = nx.from_numpy_array(auth_jac_emb, nodelist=author_list)
    author_pos = nx.spring_layout(Authors)

    if verbose:
        print("Created sparse part.")

    # Get embeddings
    pos1, pos2 = (paper_pos, author_pos) if transform_author else (author_pos, paper_pos)
    emb1 = np.array(list(pos1.values()))
    emb2 = np.array(list(pos2.values()))
    emb2_gm = np.array([np.mean([pos2[nbr] for nbr in G[node]], 0) for node in pos1.keys()])
    
    # Shove in a box in the middle
    mean1 = np.mean(emb1, 0)
    mean2 = np.mean(emb2, 0)
    emb1 -= mean1
    emb2 -= mean2
    emb2_gm -= mean2
    
    max_norm1 = np.max(np.linalg.norm(emb1, axis=1))
    max_norm2 = np.max(np.linalg.norm(emb2, axis=1))
    emb1 /= max_norm1
    emb2 /= max_norm2
    emb2_gm /= max_norm2

    # Find transformation after flipping
    emb2_gm_flipped = -emb2_gm
    R_flip, s_flip = orthogonal_procrustes(emb1, emb2_gm_flipped)
    emb2_gm_flipped_transformed = (emb2_gm_flipped @ R_flip.T) * s_flip
    mse_flip = np.mean(np.linalg.norm(emb2_gm_flipped_transformed - emb1, axis=1))

    # Find transformation without flipping
    R, s = orthogonal_procrustes(emb1, emb2_gm)
    emb2_gm_transformed = (emb2_gm @ R.T) * s
    mse_no_flip = np.mean(np.linalg.norm(emb2_gm_transformed - emb1, axis=1))

    # Flip or no flip?
    # Don't multiply by s since we want to remain at same scale
    if mse_flip < mse_no_flip:
        emb2 = ((-emb2) @ R_flip.T)
    else:
        emb2 = (emb2 @ R.T)

    # Update positions
    pos1 = {key: value for key, value in zip(pos1.keys(), emb1)}
    pos2 = {key: value for key, value in zip(pos2.keys(), emb2)}

    pos = pos1 | pos2
    return pos