import networkx as nx
import numpy as np
from .similarity_matrices import embed_papers_by_abstract, jaccard_coathorship_similarity, embed_papers_by_keywords
from networkx.utils import np_random_state
from ._tsne_grad import TSNE_GRAD

@np_random_state(10)
def two_layer_layout(
    G,
    k=None,
    pos=None,
    fixed=None,
    iterations=300,
    threshold=1e-4,
    weight="weight",
    scale=1,
    center=None,
    dim=2,
    seed=None,
    layer_dist=1,
    paper_lr=1,
    author_lr=1,
    p2a_lr=1,
    paper_type='Paper',
    author_type='Author',
    embed_papers_by='abstract', # either 'abstract' or 'keywords
    paper_embed_data_loc='Abstract'
):
    """
    The Bipartite graph of Paper and Author nodes is embedded by the force-directed Fruchtermann-Reingold algorithm.
    However, several changes are made to the algorithm. Firstly, Paper and Author nodes are initially placed on two
    separate, parallel planes. In each iteration, Paper-Author forces are calculated using the Fruchtermann-Reingold
    algorithm, but the forces perpendicular to the two planes are ignored before applying the forces, so that nodes
    stay in their respective planes. Meanwhile, additional Paper-Paper and Author-Author forces are also applied each
    iteration in an attempt to also preserve Author-Author and Paper-Paper relationships. These forces are calculated
    as follows.
    
    The Paper-Paper forces are calculated by first creating a sentence embedding of the Paper nodes (on the abstract
    or the keywords of the papers) and calculating the Barnes Hut t-SNE gradient between Paper nodes considering the
    sentence embedding to be the 'dataset' and the current position of the paper nodes to be the current embedding.
    This gradient is scaled appropriately (NOTE 'appropriately'; need to figure out the optimal scale) and applied
    as a force between paper nodes. The Author-Author forces are similarly calculated by getting the Barnes Hut t-SNE
    gradient considering the desired distance matrix to be the distance matrix generated by getting 1 - the Jaccard
    similarity of the coauthorship of papers between two Authors. These three forces are thus simultaneously applied
    for multiple iterations until an optimal embedding is achieved.
    """

    G, center = _process_params(G, center, dim + 1) # Additional dimension for two layers

    if fixed is not None:
        if pos is None:
            raise ValueError("nodes are fixed without positions given")
        for node in fixed:
            if node not in pos:
                raise ValueError("nodes are fixed without positions given")
        nfixed = {node: i for i, node in enumerate(G)}
        fixed = np.asarray([nfixed[node] for node in fixed if node in nfixed])

    node_to_idx = {node: i for i, node in enumerate(G)}
    author_idxs = [node_to_idx[node] for node in G.nodes() if G.nodes[node]['type'] == author_type]
    paper_idxs = [node_to_idx[node] for node in G.nodes() if G.nodes[node]['type'] == paper_type]

    # Initial positions
    if pos is not None:
        dom_size = max(coord for pos_tup in pos.values() for coord in pos_tup)
        if dom_size == 0:
            dom_size = 1
    else:
        dom_size = 10
    pos_arr = seed.rand(len(G), dim + 1) * dom_size + center
    pos_arr[:, -1][paper_idxs] = 0
    pos_arr[:, -1][author_idxs] = layer_dist

    if pos is not None:
        for i, n in enumerate(G):
            if n in pos:
                pos_arr[i] = np.append(pos[n], 0 if node_to_idx[n] in paper_idxs else layer_dist)



    # Get sentence embedding for papers
    if embed_papers_by == 'abstract' or embed_papers_by == "data":
        paper_embed_method = embed_papers_by_abstract
    elif embed_papers_by == 'keywords':
        paper_embed_method = embed_papers_by_keywords
    else:
        raise ValueError(f"self.embed_papers_by has to be one of 'abstract' or 'keywords'. Instead got {embed_papers_by}")
    
    node_to_vec = paper_embed_method(G, False, paper_embed_data_loc, paper_type)
    paper_emb = [None] * len(paper_idxs)
    for node, vec in node_to_vec.items():
        idx = paper_idxs.index(node_to_idx[node])
        paper_emb[idx] = vec
    paper_emb = np.array(paper_emb)

    # Get jaccard dissimilarity matrix for authors
    auth_dist, node_list = jaccard_coathorship_similarity(G, ret_nodelist=True,author_type=author_type)
    j2og_idxs = [author_idxs.index(node_to_idx[node]) for node in node_list]
    og2j_idx = [None] * len(author_idxs)
    for j_idx, og_idx in enumerate(j2og_idxs):
        og2j_idx[og_idx] = j_idx

    auth_dist = auth_dist[og2j_idx][:, og2j_idx]
    auth_dist = 1 - auth_dist
    

    if len(G) == 0:
        return {}
    if len(G) == 1:
        return {nx.utils.arbitrary_element(G.nodes()): center}

    try:
        raise ValueError # TODO: implement sparse solver for two layer approach
        # Sparse matrix
        if len(G) < 500:  # sparse solver for large graphs
            raise ValueError
        Adj = nx.to_scipy_sparse_array(G, weight=weight, dtype="f")
        if k is None and fixed is not None:
            # We must adjust k by domain size for layouts not near 1x1
            nnodes, _ = Adj.shape
            k = dom_size / np.sqrt(nnodes)
        pos = _sparse_fruchterman_reingold(
            Adj, k, pos_arr, fixed, iterations, threshold, dim, seed # NOTE should it be dim + 1? Check after reading fruchtermann reingold code
        )
    except ValueError:
        Adj = nx.to_numpy_array(G, weight=weight)
        if k is None and fixed is not None:
            # We must adjust k by domain size for layouts not near 1x1
            nnodes, _ = Adj.shape
            k = dom_size / np.sqrt(nnodes)
        pos = _fruchterman_reingold(
            Adj, pos_arr,
            paper_emb, auth_dist,
            paper_idxs, author_idxs,
            k, fixed, iterations, threshold, dim  + 1, seed,
            paper_lr, author_lr, p2a_lr
        )
    if fixed is None and scale is not None:
        pos = rescale_layout(pos, scale=scale) + center
    pos = pos[:, :2]
    pos = dict(zip(G, pos))
    return pos

@np_random_state(10)
def _fruchterman_reingold(
    Adj, pos,
    paper_emb, author_dist,
    paper_idxs, author_idxs,
    k=None, fixed=None, iterations=50, threshold=1e-4, dim=2, seed=None,
    paper_lr=1, author_lr=1, p2a_lr=1,
):
    # Position nodes in adjacency matrix A using Fruchterman-Reingold
    # Entry point for NetworkX graph is fruchterman_reingold_layout()

    try:
        nnodes, _ = Adj.shape
    except AttributeError as err:
        msg = "fruchterman_reingold() takes an adjacency matrix as input"
        raise nx.NetworkXError(msg) from err


    # optimal distance between nodes
    if k is None:
        k = np.sqrt(1.0 / nnodes)
    # the initial "temperature"  is about .1 of domain area (=1x1)
    # this is the largest step allowed in the dynamics.
    # We need to calculate this in case our fixed positions force our domain
    # to be much bigger than 1x1
    t = max(max(pos.T[0]) - min(pos.T[0]), max(pos.T[1]) - min(pos.T[1])) * 0.1
    # simple cooling scheme.
    # linearly step down by dt on each iteration so last iteration is size dt.
    dt = t / (iterations + 1)
    delta = np.zeros((pos.shape[0], pos.shape[0], pos.shape[1]), dtype=Adj.dtype)
    # the inscrutable (but fast) version
    # this is still O(V^2)
    # could use multilevel methods to speed this up significantly
    for iteration in range(iterations):
        # matrix of difference between points
        delta = pos[:, np.newaxis, :] - pos[np.newaxis, :, :]
        # distance between points
        distance = np.linalg.norm(delta, axis=-1)
        # enforce minimum distance of 0.01
        np.clip(distance, 0.01, None, out=distance)
        # displacement "force"
        displacement = np.einsum(
            "ijk,ij->ik", delta, (k * k / distance**2 - Adj * distance / k)
        )
        # update positions
        length = np.linalg.norm(displacement, axis=-1)
        length = np.where(length < 0.01, 0.1, length)
        delta_pos = np.einsum("ij,i->ij", displacement, t / length)
        if fixed is not None:
            # don't change positions of fixed nodes
            delta_pos[fixed] = 0.0

        # Ignore forces perpendicular to the two layers
        delta_pos[:, -1] = 0.0
        max_delta = np.max(np.linalg.norm(delta_pos, axis=1))
        # delta_pos /= max_delta
        # print(max_delta)

        # Update author embedding
        auth_pos = pos[author_idxs]
        auth_update = TSNE_GRAD(metric='precomputed', n_components=pos.shape[1]).get_grad(author_dist, auth_pos)
        auth_update /= np.max(np.linalg.norm(auth_update, axis=1)) * max_delta

        # Update paper embedding
        paper_pos = pos[paper_idxs]
        paper_update = TSNE_GRAD(metric='euclidean', n_components=pos.shape[1]).get_grad(paper_emb, paper_pos)
        paper_update /= np.max(np.linalg.norm(paper_update, axis=1)) * max_delta
        
        pos += delta_pos * p2a_lr
        pos[author_idxs] += auth_update * author_lr
        pos[paper_idxs] += paper_update * paper_lr
        # cool temperature
        t -= dt
        # if iteration % 50 == 0: print(iteration) # TODO rem
        if (np.all(paper_update.flatten() < 1e-12) and np.all(auth_update.flatten() < 1e-12) and np.all(delta_pos.flatten() < 1e-12)):
            print(f"All gradients are very small. Stopped at {iteration + 1} iterations.")
            break
        if (np.linalg.norm(delta_pos) / nnodes) < threshold:
            print(f'Stopped algorithm at {iteration + 1} iterations.')
            break
    else:
        print(f'Completed algorithm with {iteration + 1} iterations.')
    
    return pos

def _sparse_fruchterman_reingold(
    A, k=None, pos=None, fixed=None, iterations=50, threshold=1e-4, dim=2, seed=None
):
    # Position nodes in adjacency matrix A using Fruchterman-Reingold
    # Entry point for NetworkX graph is fruchterman_reingold_layout()
    # Sparse version
    import numpy as np
    import scipy as sp

    try:
        nnodes, _ = A.shape
    except AttributeError as err:
        msg = "fruchterman_reingold() takes an adjacency matrix as input"
        raise nx.NetworkXError(msg) from err
    # make sure we have a LIst of Lists representation
    try:
        A = A.tolil()
    except AttributeError:
        A = (sp.sparse.coo_array(A)).tolil()

    if pos is None:
        # random initial positions
        pos = np.asarray(seed.rand(nnodes, dim), dtype=A.dtype)
    else:
        # make sure positions are of same type as matrix
        pos = pos.astype(A.dtype)

    # no fixed nodes
    if fixed is None:
        fixed = []

    # optimal distance between nodes
    if k is None:
        k = np.sqrt(1.0 / nnodes)
    # the initial "temperature"  is about .1 of domain area (=1x1)
    # this is the largest step allowed in the dynamics.
    t = max(max(pos.T[0]) - min(pos.T[0]), max(pos.T[1]) - min(pos.T[1])) * 0.1
    # simple cooling scheme.
    # linearly step down by dt on each iteration so last iteration is size dt.
    dt = t / (iterations + 1)

    displacement = np.zeros((dim, nnodes))
    for iteration in range(iterations):
        displacement *= 0
        # loop over rows
        for i in range(A.shape[0]):
            if i in fixed:
                continue
            # difference between this row's node position and all others
            delta = (pos[i] - pos).T
            # distance between points
            distance = np.sqrt((delta**2).sum(axis=0))
            # enforce minimum distance of 0.01
            distance = np.where(distance < 0.01, 0.01, distance)
            # the adjacency matrix row
            Ai = A.getrowview(i).toarray()  # TODO: revisit w/ sparse 1D container
            # displacement "force"
            displacement[:, i] += (
                delta * (k * k / distance**2 - Ai * distance / k)
            ).sum(axis=1)
        # update positions
        length = np.sqrt((displacement**2).sum(axis=0))
        length = np.where(length < 0.01, 0.1, length)
        delta_pos = (displacement * t / length).T
        pos += delta_pos
        # cool temperature
        t -= dt
        if (np.linalg.norm(delta_pos) / nnodes) < threshold:
            break
    return pos




def _process_params(G, center, dim):
    # Some boilerplate code.
    import numpy as np

    if not isinstance(G, nx.Graph):
        empty_graph = nx.Graph()
        empty_graph.add_nodes_from(G)
        G = empty_graph

    if center is None:
        center = np.zeros(dim)
    else:
        center = np.asarray(center)

    if len(center) != dim:
        msg = "length of center coordinates must match dimension of layout"
        raise ValueError(msg)

    return G, center


def rescale_layout(pos, scale=1):
    """Returns scaled position array to (-scale, scale) in all axes.

    The function acts on NumPy arrays which hold position information.
    Each position is one row of the array. The dimension of the space
    equals the number of columns. Each coordinate in one column.

    To rescale, the mean (center) is subtracted from each axis separately.
    Then all values are scaled so that the largest magnitude value
    from all axes equals `scale` (thus, the aspect ratio is preserved).
    The resulting NumPy Array is returned (order of rows unchanged).

    Parameters
    ----------
    pos : numpy array
        positions to be scaled. Each row is a position.

    scale : number (default: 1)
        The size of the resulting extent in all directions.

    Returns
    -------
    pos : numpy array
        scaled positions. Each row is a position.

    See Also
    --------
    rescale_layout_dict
    """
    import numpy as np

    # Find max length over all dimensions
    pos -= pos.mean(axis=0)
    lim = np.abs(pos).max()  # max coordinate for all axes
    # rescale to (-scale, scale) in all directions, preserves aspect
    if lim > 0:
        pos *= scale / lim
    return pos

if __name__ == "__main__":
    VAST_G = nx.read_graphml(f"raw_data/vispub/VAST_graph.graphml")
    coords = two_layer_layout(VAST_G)

    import matplotlib.pyplot as plt
    def plot_coords(G, coords):
        fig, ax = plt.subplots()
        for node, coord in coords.items():
            ax.scatter(coord[0], coord[1], label=node)
        for node1, node2 in G.edges():
            to_plot = np.array([coords[node1], coords[node2]])
            ax.plot(to_plot[:, 0], to_plot[:, 1], c='black')
        ax.legend()

    plot_coords(VAST_G, coords)

    